title: 'TryHackMe Room Log'
description: 'A retro terminal-style log documenting my TryHackMe adventures, one room at a time...'
# theme: jekyll-theme-hacker
markdown: kramdown
design_mode: true
baseurl: '/tryhackme-log' # because this is a project site
url: 'https://vanessa-ayer.github.io'
show_excerpts: false
author: ''
# TryHackMe metadata (edit these as you progress)
thm:
  rank: 'Pathfinder' # your current rank
  points: 380 # total points
  next_rank: 'Seeker' # next rank label
  progress_pct: 35 # 0–100 progress to the next rank

